wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.8.2
      5: 0.10.32
      8:
      - 3
      - 5
experiment.hidden_dim_1:
  desc: null
  value: 360
experiment.hidden_dim_2:
  desc: null
  value: 254
experiment.hidden_dim_3:
  desc: null
  value: 173
experiment.lr:
  desc: null
  value: 0.003
